# +----------------------------------------------------+
# <                 Bot Configuration                  >
# <               All bot configuration                >
# +----------------------------------------------------+

# Bot token can be found on your
# Discord application page.
Bot_Token: MzkzMTcyNTE5MzQ5MTI1MTIx.Df5mMg.31BQVBZgPUeSqNnjZIeKZXDqST4

# Bot ID, this is also known as Client ID
# on your Discord application page.
Bot_ID: '455265947767537664'

# Owner ID of the owner of the bot, server, or guild.
# You can easily get your id by right
# clicking your self and copy id.
# This only works when developer mode is enabled.
# Go to settings>appearance and enable developer mode
Owner_ID: '279693570430992386'

# Set of character that distinguish if it''s a command.
Command_Trigger: '%%'

# Should bot''s command responses be deleted after 5 minutes?
Delete_Response: true

# What language should the bot respond with
Localization: en

# This will be the game of the bot
# and will be shown under the name
# of the bot as "Playing <Default_Game>"
Default_Game: Minecraft Server Xtreme Edition
