# +----------------------------------------------------+
# <             Mod Channel Configuration              >
# <           All mod channel configuration            >
# +----------------------------------------------------+

# ID of the text channel you want to make as a mod channel
# Leave it blank if you don''t want a mod channel
# Do you want to prevent messages that
# are being sent on the mod channel
# to be relayed to Minecraft?
One_Way: false

# Do you want to see in-game chat on a mod channel?
See_Chat: true

# Will player join event broadcast be relayed to Mod MCBChannel?
See_Player_Join: true

# Will player quit event broadcast be relayed to Mod MCBChannel?
See_Player_Quit: true

# Will player death event broadcast be relayed to Mod MCBChannel?
See_Player_Death: true

# Do you want to see commands that
# are being executed on a mod channel?
See_Commands: true

# Do you want to see messages that
# have been cancelled by other plugin?
# Cancelled messages are considered
# a private message
See_Cancelled_Chats: true

# Do you want to see player chat that
# have been GriefPrevention soft muted.
See_GriefPrevention_SoftMute: true

# Do you want to see mcMMO Admin chat?
See_mcMMO_Admin_Chat: true

# Do you want to see mcMMO Party chat?
See_mcMMO_Party_Chat: true

# Do you want to see fake join/leave messages
# from SuperVanish on a mod channel?
# Will be marked "(Vanish)"
See_SV: true

# Do you want to see broadcasts on a mod channel?
See_Broadcast: true

# ID of the text channel you want to make as a mod channel
# Leave it blank if you don''t want a mod channel
# ID of the text channel you want to make as a mod channel
# Leave it blank if you don''t want a mod channel
Mod_Channels:
- '123123123'
- '123123123'
